name: Allan Purba
favicon: null
layout_spectrum: 0
typography_spectrum: 0.59477
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#010101'
    - '#232323'
    - '#909090'
    - '#c1c1c1'
    - '#e3e3e3'
  brandStrength: 0.75
  lightness: 0
  saturation: 0.00760459084995091
  rhythmicContrast: 0.25
purpose: []
